/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as ForosRouteImport } from './routes/foros'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForosCourseIdRouteImport } from './routes/foros.$courseId'
import { Route as CursoCourseIdRouteImport } from './routes/curso.$courseId'

const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const ForosRoute = ForosRouteImport.update({
  id: '/foros',
  path: '/foros',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForosCourseIdRoute = ForosCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => ForosRoute,
} as any)
const CursoCourseIdRoute = CursoCourseIdRouteImport.update({
  id: '/curso/$courseId',
  path: '/curso/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cursos': typeof CursosRoute
  '/foros': typeof ForosRouteWithChildren
  '/metas': typeof MetasRoute
  '/curso/$courseId': typeof CursoCourseIdRoute
  '/foros/$courseId': typeof ForosCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cursos': typeof CursosRoute
  '/foros': typeof ForosRouteWithChildren
  '/metas': typeof MetasRoute
  '/curso/$courseId': typeof CursoCourseIdRoute
  '/foros/$courseId': typeof ForosCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cursos': typeof CursosRoute
  '/foros': typeof ForosRouteWithChildren
  '/metas': typeof MetasRoute
  '/curso/$courseId': typeof CursoCourseIdRoute
  '/foros/$courseId': typeof ForosCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cursos'
    | '/foros'
    | '/metas'
    | '/curso/$courseId'
    | '/foros/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cursos'
    | '/foros'
    | '/metas'
    | '/curso/$courseId'
    | '/foros/$courseId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cursos'
    | '/foros'
    | '/metas'
    | '/curso/$courseId'
    | '/foros/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CursosRoute: typeof CursosRoute
  ForosRoute: typeof ForosRouteWithChildren
  MetasRoute: typeof MetasRoute
  CursoCourseIdRoute: typeof CursoCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foros': {
      id: '/foros'
      path: '/foros'
      fullPath: '/foros'
      preLoaderRoute: typeof ForosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foros/$courseId': {
      id: '/foros/$courseId'
      path: '/$courseId'
      fullPath: '/foros/$courseId'
      preLoaderRoute: typeof ForosCourseIdRouteImport
      parentRoute: typeof ForosRoute
    }
    '/curso/$courseId': {
      id: '/curso/$courseId'
      path: '/curso/$courseId'
      fullPath: '/curso/$courseId'
      preLoaderRoute: typeof CursoCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ForosRouteChildren {
  ForosCourseIdRoute: typeof ForosCourseIdRoute
}

const ForosRouteChildren: ForosRouteChildren = {
  ForosCourseIdRoute: ForosCourseIdRoute,
}

const ForosRouteWithChildren = ForosRoute._addFileChildren(ForosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CursosRoute: CursosRoute,
  ForosRoute: ForosRouteWithChildren,
  MetasRoute: MetasRoute,
  CursoCourseIdRoute: CursoCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
