ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "gender"    VARCHAR(20);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "skinTone"  VARCHAR(20);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "birthYear" INTEGER;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "activity"  VARCHAR(50);
